services:
  - type: web
    name: eventbook-backend
    env: node
    plan: free
    autoDeploy: true
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      # Set the following in Render Dashboard (do not commit secrets)
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
